/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsNotificationsRouteImport } from './routes/settings/notifications'
import { Route as RouterIdRouteRouteImport } from './routes/router/$id/route'
import { Route as RouterIdIndexRouteImport } from './routes/router/$id/index'
import { Route as SettingsNotificationsWebhooksRouteImport } from './routes/settings/notifications/webhooks'
import { Route as RouterIdVlansRouteImport } from './routes/router/$id/vlans'
import { Route as RouterIdRoutingRouteImport } from './routes/router/$id/routing'
import { Route as RouterIdPluginsRouteImport } from './routes/router/$id/plugins'
import { Route as RouterIdNetworkRouteImport } from './routes/router/$id/network'
import { Route as RouterIdLogsRouteImport } from './routes/router/$id/logs'
import { Route as RouterIdFirewallRouteImport } from './routes/router/$id/firewall'
import { Route as RouterIdDnsRouteImport } from './routes/router/$id/dns'
import { Route as RouterIdDhcpRouteImport } from './routes/router/$id/dhcp'
import { Route as RouterIdWifiIndexRouteImport } from './routes/router/$id/wifi/index'
import { Route as RouterIdVpnIndexRouteImport } from './routes/router/$id/vpn/index'
import { Route as RouterIdServicesIndexRouteImport } from './routes/router/$id/services/index'
import { Route as RouterIdWifiInterfaceNameRouteImport } from './routes/router/$id/wifi/$interfaceName'
import { Route as RouterIdVpnServersRouteImport } from './routes/router/$id/vpn/servers'
import { Route as RouterIdVpnClientsRouteImport } from './routes/router/$id/vpn/clients'
import { Route as RouterIdServicesTemplatesRouteImport } from './routes/router/$id/services/templates'
import { Route as RouterIdServicesInstanceIdRouteImport } from './routes/router/$id/services/$instanceId'
import { Route as RouterIdFirewallTemplatesRouteImport } from './routes/router/$id/firewall/templates'
import { Route as RouterIdFirewallServicePortsRouteImport } from './routes/router/$id/firewall/service-ports'
import { Route as RouterIdFirewallRawRouteImport } from './routes/router/$id/firewall/raw'
import { Route as RouterIdFirewallRateLimitingRouteImport } from './routes/router/$id/firewall/rate-limiting'
import { Route as RouterIdFirewallPortKnockingRouteImport } from './routes/router/$id/firewall/port-knocking'
import { Route as RouterIdFirewallMangleRouteImport } from './routes/router/$id/firewall/mangle'
import { Route as RouterIdFirewallLogsRouteImport } from './routes/router/$id/firewall/logs'
import { Route as RouterIdFirewallConnectionsRouteImport } from './routes/router/$id/firewall/connections'
import { Route as RouterIdFirewallAddressListsRouteImport } from './routes/router/$id/firewall/address-lists'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => SettingsRoute,
} as any)
const RouterIdRouteRoute = RouterIdRouteRouteImport.update({
  id: '/router/$id',
  path: '/router/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RouterIdIndexRoute = RouterIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RouterIdRouteRoute,
} as any)
const SettingsNotificationsWebhooksRoute =
  SettingsNotificationsWebhooksRouteImport.update({
    id: '/webhooks',
    path: '/webhooks',
    getParentRoute: () => SettingsNotificationsRoute,
  } as any)
const RouterIdVlansRoute = RouterIdVlansRouteImport.update({
  id: '/vlans',
  path: '/vlans',
  getParentRoute: () => RouterIdRouteRoute,
} as any)
const RouterIdRoutingRoute = RouterIdRoutingRouteImport.update({
  id: '/routing',
  path: '/routing',
  getParentRoute: () => RouterIdRouteRoute,
} as any)
const RouterIdPluginsRoute = RouterIdPluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => RouterIdRouteRoute,
} as any)
const RouterIdNetworkRoute = RouterIdNetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => RouterIdRouteRoute,
} as any)
const RouterIdLogsRoute = RouterIdLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => RouterIdRouteRoute,
} as any)
const RouterIdFirewallRoute = RouterIdFirewallRouteImport.update({
  id: '/firewall',
  path: '/firewall',
  getParentRoute: () => RouterIdRouteRoute,
} as any)
const RouterIdDnsRoute = RouterIdDnsRouteImport.update({
  id: '/dns',
  path: '/dns',
  getParentRoute: () => RouterIdRouteRoute,
} as any)
const RouterIdDhcpRoute = RouterIdDhcpRouteImport.update({
  id: '/dhcp',
  path: '/dhcp',
  getParentRoute: () => RouterIdRouteRoute,
} as any)
const RouterIdWifiIndexRoute = RouterIdWifiIndexRouteImport.update({
  id: '/wifi/',
  path: '/wifi/',
  getParentRoute: () => RouterIdRouteRoute,
} as any)
const RouterIdVpnIndexRoute = RouterIdVpnIndexRouteImport.update({
  id: '/vpn/',
  path: '/vpn/',
  getParentRoute: () => RouterIdRouteRoute,
} as any)
const RouterIdServicesIndexRoute = RouterIdServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => RouterIdRouteRoute,
} as any)
const RouterIdWifiInterfaceNameRoute =
  RouterIdWifiInterfaceNameRouteImport.update({
    id: '/wifi/$interfaceName',
    path: '/wifi/$interfaceName',
    getParentRoute: () => RouterIdRouteRoute,
  } as any)
const RouterIdVpnServersRoute = RouterIdVpnServersRouteImport.update({
  id: '/vpn/servers',
  path: '/vpn/servers',
  getParentRoute: () => RouterIdRouteRoute,
} as any)
const RouterIdVpnClientsRoute = RouterIdVpnClientsRouteImport.update({
  id: '/vpn/clients',
  path: '/vpn/clients',
  getParentRoute: () => RouterIdRouteRoute,
} as any)
const RouterIdServicesTemplatesRoute =
  RouterIdServicesTemplatesRouteImport.update({
    id: '/services/templates',
    path: '/services/templates',
    getParentRoute: () => RouterIdRouteRoute,
  } as any)
const RouterIdServicesInstanceIdRoute =
  RouterIdServicesInstanceIdRouteImport.update({
    id: '/services/$instanceId',
    path: '/services/$instanceId',
    getParentRoute: () => RouterIdRouteRoute,
  } as any)
const RouterIdFirewallTemplatesRoute =
  RouterIdFirewallTemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => RouterIdFirewallRoute,
  } as any)
const RouterIdFirewallServicePortsRoute =
  RouterIdFirewallServicePortsRouteImport.update({
    id: '/service-ports',
    path: '/service-ports',
    getParentRoute: () => RouterIdFirewallRoute,
  } as any)
const RouterIdFirewallRawRoute = RouterIdFirewallRawRouteImport.update({
  id: '/raw',
  path: '/raw',
  getParentRoute: () => RouterIdFirewallRoute,
} as any)
const RouterIdFirewallRateLimitingRoute =
  RouterIdFirewallRateLimitingRouteImport.update({
    id: '/rate-limiting',
    path: '/rate-limiting',
    getParentRoute: () => RouterIdFirewallRoute,
  } as any)
const RouterIdFirewallPortKnockingRoute =
  RouterIdFirewallPortKnockingRouteImport.update({
    id: '/port-knocking',
    path: '/port-knocking',
    getParentRoute: () => RouterIdFirewallRoute,
  } as any)
const RouterIdFirewallMangleRoute = RouterIdFirewallMangleRouteImport.update({
  id: '/mangle',
  path: '/mangle',
  getParentRoute: () => RouterIdFirewallRoute,
} as any)
const RouterIdFirewallLogsRoute = RouterIdFirewallLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => RouterIdFirewallRoute,
} as any)
const RouterIdFirewallConnectionsRoute =
  RouterIdFirewallConnectionsRouteImport.update({
    id: '/connections',
    path: '/connections',
    getParentRoute: () => RouterIdFirewallRoute,
  } as any)
const RouterIdFirewallAddressListsRoute =
  RouterIdFirewallAddressListsRouteImport.update({
    id: '/address-lists',
    path: '/address-lists',
    getParentRoute: () => RouterIdFirewallRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteWithChildren
  '/router/$id': typeof RouterIdRouteRouteWithChildren
  '/settings/notifications': typeof SettingsNotificationsRouteWithChildren
  '/router/$id/dhcp': typeof RouterIdDhcpRoute
  '/router/$id/dns': typeof RouterIdDnsRoute
  '/router/$id/firewall': typeof RouterIdFirewallRouteWithChildren
  '/router/$id/logs': typeof RouterIdLogsRoute
  '/router/$id/network': typeof RouterIdNetworkRoute
  '/router/$id/plugins': typeof RouterIdPluginsRoute
  '/router/$id/routing': typeof RouterIdRoutingRoute
  '/router/$id/vlans': typeof RouterIdVlansRoute
  '/settings/notifications/webhooks': typeof SettingsNotificationsWebhooksRoute
  '/router/$id/': typeof RouterIdIndexRoute
  '/router/$id/firewall/address-lists': typeof RouterIdFirewallAddressListsRoute
  '/router/$id/firewall/connections': typeof RouterIdFirewallConnectionsRoute
  '/router/$id/firewall/logs': typeof RouterIdFirewallLogsRoute
  '/router/$id/firewall/mangle': typeof RouterIdFirewallMangleRoute
  '/router/$id/firewall/port-knocking': typeof RouterIdFirewallPortKnockingRoute
  '/router/$id/firewall/rate-limiting': typeof RouterIdFirewallRateLimitingRoute
  '/router/$id/firewall/raw': typeof RouterIdFirewallRawRoute
  '/router/$id/firewall/service-ports': typeof RouterIdFirewallServicePortsRoute
  '/router/$id/firewall/templates': typeof RouterIdFirewallTemplatesRoute
  '/router/$id/services/$instanceId': typeof RouterIdServicesInstanceIdRoute
  '/router/$id/services/templates': typeof RouterIdServicesTemplatesRoute
  '/router/$id/vpn/clients': typeof RouterIdVpnClientsRoute
  '/router/$id/vpn/servers': typeof RouterIdVpnServersRoute
  '/router/$id/wifi/$interfaceName': typeof RouterIdWifiInterfaceNameRoute
  '/router/$id/services/': typeof RouterIdServicesIndexRoute
  '/router/$id/vpn/': typeof RouterIdVpnIndexRoute
  '/router/$id/wifi/': typeof RouterIdWifiIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings/notifications': typeof SettingsNotificationsRouteWithChildren
  '/router/$id/dhcp': typeof RouterIdDhcpRoute
  '/router/$id/dns': typeof RouterIdDnsRoute
  '/router/$id/firewall': typeof RouterIdFirewallRouteWithChildren
  '/router/$id/logs': typeof RouterIdLogsRoute
  '/router/$id/network': typeof RouterIdNetworkRoute
  '/router/$id/plugins': typeof RouterIdPluginsRoute
  '/router/$id/routing': typeof RouterIdRoutingRoute
  '/router/$id/vlans': typeof RouterIdVlansRoute
  '/settings/notifications/webhooks': typeof SettingsNotificationsWebhooksRoute
  '/router/$id': typeof RouterIdIndexRoute
  '/router/$id/firewall/address-lists': typeof RouterIdFirewallAddressListsRoute
  '/router/$id/firewall/connections': typeof RouterIdFirewallConnectionsRoute
  '/router/$id/firewall/logs': typeof RouterIdFirewallLogsRoute
  '/router/$id/firewall/mangle': typeof RouterIdFirewallMangleRoute
  '/router/$id/firewall/port-knocking': typeof RouterIdFirewallPortKnockingRoute
  '/router/$id/firewall/rate-limiting': typeof RouterIdFirewallRateLimitingRoute
  '/router/$id/firewall/raw': typeof RouterIdFirewallRawRoute
  '/router/$id/firewall/service-ports': typeof RouterIdFirewallServicePortsRoute
  '/router/$id/firewall/templates': typeof RouterIdFirewallTemplatesRoute
  '/router/$id/services/$instanceId': typeof RouterIdServicesInstanceIdRoute
  '/router/$id/services/templates': typeof RouterIdServicesTemplatesRoute
  '/router/$id/vpn/clients': typeof RouterIdVpnClientsRoute
  '/router/$id/vpn/servers': typeof RouterIdVpnServersRoute
  '/router/$id/wifi/$interfaceName': typeof RouterIdWifiInterfaceNameRoute
  '/router/$id/services': typeof RouterIdServicesIndexRoute
  '/router/$id/vpn': typeof RouterIdVpnIndexRoute
  '/router/$id/wifi': typeof RouterIdWifiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteWithChildren
  '/router/$id': typeof RouterIdRouteRouteWithChildren
  '/settings/notifications': typeof SettingsNotificationsRouteWithChildren
  '/router/$id/dhcp': typeof RouterIdDhcpRoute
  '/router/$id/dns': typeof RouterIdDnsRoute
  '/router/$id/firewall': typeof RouterIdFirewallRouteWithChildren
  '/router/$id/logs': typeof RouterIdLogsRoute
  '/router/$id/network': typeof RouterIdNetworkRoute
  '/router/$id/plugins': typeof RouterIdPluginsRoute
  '/router/$id/routing': typeof RouterIdRoutingRoute
  '/router/$id/vlans': typeof RouterIdVlansRoute
  '/settings/notifications/webhooks': typeof SettingsNotificationsWebhooksRoute
  '/router/$id/': typeof RouterIdIndexRoute
  '/router/$id/firewall/address-lists': typeof RouterIdFirewallAddressListsRoute
  '/router/$id/firewall/connections': typeof RouterIdFirewallConnectionsRoute
  '/router/$id/firewall/logs': typeof RouterIdFirewallLogsRoute
  '/router/$id/firewall/mangle': typeof RouterIdFirewallMangleRoute
  '/router/$id/firewall/port-knocking': typeof RouterIdFirewallPortKnockingRoute
  '/router/$id/firewall/rate-limiting': typeof RouterIdFirewallRateLimitingRoute
  '/router/$id/firewall/raw': typeof RouterIdFirewallRawRoute
  '/router/$id/firewall/service-ports': typeof RouterIdFirewallServicePortsRoute
  '/router/$id/firewall/templates': typeof RouterIdFirewallTemplatesRoute
  '/router/$id/services/$instanceId': typeof RouterIdServicesInstanceIdRoute
  '/router/$id/services/templates': typeof RouterIdServicesTemplatesRoute
  '/router/$id/vpn/clients': typeof RouterIdVpnClientsRoute
  '/router/$id/vpn/servers': typeof RouterIdVpnServersRoute
  '/router/$id/wifi/$interfaceName': typeof RouterIdWifiInterfaceNameRoute
  '/router/$id/services/': typeof RouterIdServicesIndexRoute
  '/router/$id/vpn/': typeof RouterIdVpnIndexRoute
  '/router/$id/wifi/': typeof RouterIdWifiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/router/$id'
    | '/settings/notifications'
    | '/router/$id/dhcp'
    | '/router/$id/dns'
    | '/router/$id/firewall'
    | '/router/$id/logs'
    | '/router/$id/network'
    | '/router/$id/plugins'
    | '/router/$id/routing'
    | '/router/$id/vlans'
    | '/settings/notifications/webhooks'
    | '/router/$id/'
    | '/router/$id/firewall/address-lists'
    | '/router/$id/firewall/connections'
    | '/router/$id/firewall/logs'
    | '/router/$id/firewall/mangle'
    | '/router/$id/firewall/port-knocking'
    | '/router/$id/firewall/rate-limiting'
    | '/router/$id/firewall/raw'
    | '/router/$id/firewall/service-ports'
    | '/router/$id/firewall/templates'
    | '/router/$id/services/$instanceId'
    | '/router/$id/services/templates'
    | '/router/$id/vpn/clients'
    | '/router/$id/vpn/servers'
    | '/router/$id/wifi/$interfaceName'
    | '/router/$id/services/'
    | '/router/$id/vpn/'
    | '/router/$id/wifi/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/settings/notifications'
    | '/router/$id/dhcp'
    | '/router/$id/dns'
    | '/router/$id/firewall'
    | '/router/$id/logs'
    | '/router/$id/network'
    | '/router/$id/plugins'
    | '/router/$id/routing'
    | '/router/$id/vlans'
    | '/settings/notifications/webhooks'
    | '/router/$id'
    | '/router/$id/firewall/address-lists'
    | '/router/$id/firewall/connections'
    | '/router/$id/firewall/logs'
    | '/router/$id/firewall/mangle'
    | '/router/$id/firewall/port-knocking'
    | '/router/$id/firewall/rate-limiting'
    | '/router/$id/firewall/raw'
    | '/router/$id/firewall/service-ports'
    | '/router/$id/firewall/templates'
    | '/router/$id/services/$instanceId'
    | '/router/$id/services/templates'
    | '/router/$id/vpn/clients'
    | '/router/$id/vpn/servers'
    | '/router/$id/wifi/$interfaceName'
    | '/router/$id/services'
    | '/router/$id/vpn'
    | '/router/$id/wifi'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/router/$id'
    | '/settings/notifications'
    | '/router/$id/dhcp'
    | '/router/$id/dns'
    | '/router/$id/firewall'
    | '/router/$id/logs'
    | '/router/$id/network'
    | '/router/$id/plugins'
    | '/router/$id/routing'
    | '/router/$id/vlans'
    | '/settings/notifications/webhooks'
    | '/router/$id/'
    | '/router/$id/firewall/address-lists'
    | '/router/$id/firewall/connections'
    | '/router/$id/firewall/logs'
    | '/router/$id/firewall/mangle'
    | '/router/$id/firewall/port-knocking'
    | '/router/$id/firewall/rate-limiting'
    | '/router/$id/firewall/raw'
    | '/router/$id/firewall/service-ports'
    | '/router/$id/firewall/templates'
    | '/router/$id/services/$instanceId'
    | '/router/$id/services/templates'
    | '/router/$id/vpn/clients'
    | '/router/$id/vpn/servers'
    | '/router/$id/wifi/$interfaceName'
    | '/router/$id/services/'
    | '/router/$id/vpn/'
    | '/router/$id/wifi/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  RouterIdRouteRoute: typeof RouterIdRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/router/$id': {
      id: '/router/$id'
      path: '/router/$id'
      fullPath: '/router/$id'
      preLoaderRoute: typeof RouterIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/router/$id/': {
      id: '/router/$id/'
      path: '/'
      fullPath: '/router/$id/'
      preLoaderRoute: typeof RouterIdIndexRouteImport
      parentRoute: typeof RouterIdRouteRoute
    }
    '/settings/notifications/webhooks': {
      id: '/settings/notifications/webhooks'
      path: '/webhooks'
      fullPath: '/settings/notifications/webhooks'
      preLoaderRoute: typeof SettingsNotificationsWebhooksRouteImport
      parentRoute: typeof SettingsNotificationsRoute
    }
    '/router/$id/vlans': {
      id: '/router/$id/vlans'
      path: '/vlans'
      fullPath: '/router/$id/vlans'
      preLoaderRoute: typeof RouterIdVlansRouteImport
      parentRoute: typeof RouterIdRouteRoute
    }
    '/router/$id/routing': {
      id: '/router/$id/routing'
      path: '/routing'
      fullPath: '/router/$id/routing'
      preLoaderRoute: typeof RouterIdRoutingRouteImport
      parentRoute: typeof RouterIdRouteRoute
    }
    '/router/$id/plugins': {
      id: '/router/$id/plugins'
      path: '/plugins'
      fullPath: '/router/$id/plugins'
      preLoaderRoute: typeof RouterIdPluginsRouteImport
      parentRoute: typeof RouterIdRouteRoute
    }
    '/router/$id/network': {
      id: '/router/$id/network'
      path: '/network'
      fullPath: '/router/$id/network'
      preLoaderRoute: typeof RouterIdNetworkRouteImport
      parentRoute: typeof RouterIdRouteRoute
    }
    '/router/$id/logs': {
      id: '/router/$id/logs'
      path: '/logs'
      fullPath: '/router/$id/logs'
      preLoaderRoute: typeof RouterIdLogsRouteImport
      parentRoute: typeof RouterIdRouteRoute
    }
    '/router/$id/firewall': {
      id: '/router/$id/firewall'
      path: '/firewall'
      fullPath: '/router/$id/firewall'
      preLoaderRoute: typeof RouterIdFirewallRouteImport
      parentRoute: typeof RouterIdRouteRoute
    }
    '/router/$id/dns': {
      id: '/router/$id/dns'
      path: '/dns'
      fullPath: '/router/$id/dns'
      preLoaderRoute: typeof RouterIdDnsRouteImport
      parentRoute: typeof RouterIdRouteRoute
    }
    '/router/$id/dhcp': {
      id: '/router/$id/dhcp'
      path: '/dhcp'
      fullPath: '/router/$id/dhcp'
      preLoaderRoute: typeof RouterIdDhcpRouteImport
      parentRoute: typeof RouterIdRouteRoute
    }
    '/router/$id/wifi/': {
      id: '/router/$id/wifi/'
      path: '/wifi'
      fullPath: '/router/$id/wifi/'
      preLoaderRoute: typeof RouterIdWifiIndexRouteImport
      parentRoute: typeof RouterIdRouteRoute
    }
    '/router/$id/vpn/': {
      id: '/router/$id/vpn/'
      path: '/vpn'
      fullPath: '/router/$id/vpn/'
      preLoaderRoute: typeof RouterIdVpnIndexRouteImport
      parentRoute: typeof RouterIdRouteRoute
    }
    '/router/$id/services/': {
      id: '/router/$id/services/'
      path: '/services'
      fullPath: '/router/$id/services/'
      preLoaderRoute: typeof RouterIdServicesIndexRouteImport
      parentRoute: typeof RouterIdRouteRoute
    }
    '/router/$id/wifi/$interfaceName': {
      id: '/router/$id/wifi/$interfaceName'
      path: '/wifi/$interfaceName'
      fullPath: '/router/$id/wifi/$interfaceName'
      preLoaderRoute: typeof RouterIdWifiInterfaceNameRouteImport
      parentRoute: typeof RouterIdRouteRoute
    }
    '/router/$id/vpn/servers': {
      id: '/router/$id/vpn/servers'
      path: '/vpn/servers'
      fullPath: '/router/$id/vpn/servers'
      preLoaderRoute: typeof RouterIdVpnServersRouteImport
      parentRoute: typeof RouterIdRouteRoute
    }
    '/router/$id/vpn/clients': {
      id: '/router/$id/vpn/clients'
      path: '/vpn/clients'
      fullPath: '/router/$id/vpn/clients'
      preLoaderRoute: typeof RouterIdVpnClientsRouteImport
      parentRoute: typeof RouterIdRouteRoute
    }
    '/router/$id/services/templates': {
      id: '/router/$id/services/templates'
      path: '/services/templates'
      fullPath: '/router/$id/services/templates'
      preLoaderRoute: typeof RouterIdServicesTemplatesRouteImport
      parentRoute: typeof RouterIdRouteRoute
    }
    '/router/$id/services/$instanceId': {
      id: '/router/$id/services/$instanceId'
      path: '/services/$instanceId'
      fullPath: '/router/$id/services/$instanceId'
      preLoaderRoute: typeof RouterIdServicesInstanceIdRouteImport
      parentRoute: typeof RouterIdRouteRoute
    }
    '/router/$id/firewall/templates': {
      id: '/router/$id/firewall/templates'
      path: '/templates'
      fullPath: '/router/$id/firewall/templates'
      preLoaderRoute: typeof RouterIdFirewallTemplatesRouteImport
      parentRoute: typeof RouterIdFirewallRoute
    }
    '/router/$id/firewall/service-ports': {
      id: '/router/$id/firewall/service-ports'
      path: '/service-ports'
      fullPath: '/router/$id/firewall/service-ports'
      preLoaderRoute: typeof RouterIdFirewallServicePortsRouteImport
      parentRoute: typeof RouterIdFirewallRoute
    }
    '/router/$id/firewall/raw': {
      id: '/router/$id/firewall/raw'
      path: '/raw'
      fullPath: '/router/$id/firewall/raw'
      preLoaderRoute: typeof RouterIdFirewallRawRouteImport
      parentRoute: typeof RouterIdFirewallRoute
    }
    '/router/$id/firewall/rate-limiting': {
      id: '/router/$id/firewall/rate-limiting'
      path: '/rate-limiting'
      fullPath: '/router/$id/firewall/rate-limiting'
      preLoaderRoute: typeof RouterIdFirewallRateLimitingRouteImport
      parentRoute: typeof RouterIdFirewallRoute
    }
    '/router/$id/firewall/port-knocking': {
      id: '/router/$id/firewall/port-knocking'
      path: '/port-knocking'
      fullPath: '/router/$id/firewall/port-knocking'
      preLoaderRoute: typeof RouterIdFirewallPortKnockingRouteImport
      parentRoute: typeof RouterIdFirewallRoute
    }
    '/router/$id/firewall/mangle': {
      id: '/router/$id/firewall/mangle'
      path: '/mangle'
      fullPath: '/router/$id/firewall/mangle'
      preLoaderRoute: typeof RouterIdFirewallMangleRouteImport
      parentRoute: typeof RouterIdFirewallRoute
    }
    '/router/$id/firewall/logs': {
      id: '/router/$id/firewall/logs'
      path: '/logs'
      fullPath: '/router/$id/firewall/logs'
      preLoaderRoute: typeof RouterIdFirewallLogsRouteImport
      parentRoute: typeof RouterIdFirewallRoute
    }
    '/router/$id/firewall/connections': {
      id: '/router/$id/firewall/connections'
      path: '/connections'
      fullPath: '/router/$id/firewall/connections'
      preLoaderRoute: typeof RouterIdFirewallConnectionsRouteImport
      parentRoute: typeof RouterIdFirewallRoute
    }
    '/router/$id/firewall/address-lists': {
      id: '/router/$id/firewall/address-lists'
      path: '/address-lists'
      fullPath: '/router/$id/firewall/address-lists'
      preLoaderRoute: typeof RouterIdFirewallAddressListsRouteImport
      parentRoute: typeof RouterIdFirewallRoute
    }
  }
}

interface SettingsNotificationsRouteChildren {
  SettingsNotificationsWebhooksRoute: typeof SettingsNotificationsWebhooksRoute
}

const SettingsNotificationsRouteChildren: SettingsNotificationsRouteChildren = {
  SettingsNotificationsWebhooksRoute: SettingsNotificationsWebhooksRoute,
}

const SettingsNotificationsRouteWithChildren =
  SettingsNotificationsRoute._addFileChildren(
    SettingsNotificationsRouteChildren,
  )

interface SettingsRouteChildren {
  SettingsNotificationsRoute: typeof SettingsNotificationsRouteWithChildren
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsNotificationsRoute: SettingsNotificationsRouteWithChildren,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface RouterIdFirewallRouteChildren {
  RouterIdFirewallAddressListsRoute: typeof RouterIdFirewallAddressListsRoute
  RouterIdFirewallConnectionsRoute: typeof RouterIdFirewallConnectionsRoute
  RouterIdFirewallLogsRoute: typeof RouterIdFirewallLogsRoute
  RouterIdFirewallMangleRoute: typeof RouterIdFirewallMangleRoute
  RouterIdFirewallPortKnockingRoute: typeof RouterIdFirewallPortKnockingRoute
  RouterIdFirewallRateLimitingRoute: typeof RouterIdFirewallRateLimitingRoute
  RouterIdFirewallRawRoute: typeof RouterIdFirewallRawRoute
  RouterIdFirewallServicePortsRoute: typeof RouterIdFirewallServicePortsRoute
  RouterIdFirewallTemplatesRoute: typeof RouterIdFirewallTemplatesRoute
}

const RouterIdFirewallRouteChildren: RouterIdFirewallRouteChildren = {
  RouterIdFirewallAddressListsRoute: RouterIdFirewallAddressListsRoute,
  RouterIdFirewallConnectionsRoute: RouterIdFirewallConnectionsRoute,
  RouterIdFirewallLogsRoute: RouterIdFirewallLogsRoute,
  RouterIdFirewallMangleRoute: RouterIdFirewallMangleRoute,
  RouterIdFirewallPortKnockingRoute: RouterIdFirewallPortKnockingRoute,
  RouterIdFirewallRateLimitingRoute: RouterIdFirewallRateLimitingRoute,
  RouterIdFirewallRawRoute: RouterIdFirewallRawRoute,
  RouterIdFirewallServicePortsRoute: RouterIdFirewallServicePortsRoute,
  RouterIdFirewallTemplatesRoute: RouterIdFirewallTemplatesRoute,
}

const RouterIdFirewallRouteWithChildren =
  RouterIdFirewallRoute._addFileChildren(RouterIdFirewallRouteChildren)

interface RouterIdRouteRouteChildren {
  RouterIdDhcpRoute: typeof RouterIdDhcpRoute
  RouterIdDnsRoute: typeof RouterIdDnsRoute
  RouterIdFirewallRoute: typeof RouterIdFirewallRouteWithChildren
  RouterIdLogsRoute: typeof RouterIdLogsRoute
  RouterIdNetworkRoute: typeof RouterIdNetworkRoute
  RouterIdPluginsRoute: typeof RouterIdPluginsRoute
  RouterIdRoutingRoute: typeof RouterIdRoutingRoute
  RouterIdVlansRoute: typeof RouterIdVlansRoute
  RouterIdIndexRoute: typeof RouterIdIndexRoute
  RouterIdServicesInstanceIdRoute: typeof RouterIdServicesInstanceIdRoute
  RouterIdServicesTemplatesRoute: typeof RouterIdServicesTemplatesRoute
  RouterIdVpnClientsRoute: typeof RouterIdVpnClientsRoute
  RouterIdVpnServersRoute: typeof RouterIdVpnServersRoute
  RouterIdWifiInterfaceNameRoute: typeof RouterIdWifiInterfaceNameRoute
  RouterIdServicesIndexRoute: typeof RouterIdServicesIndexRoute
  RouterIdVpnIndexRoute: typeof RouterIdVpnIndexRoute
  RouterIdWifiIndexRoute: typeof RouterIdWifiIndexRoute
}

const RouterIdRouteRouteChildren: RouterIdRouteRouteChildren = {
  RouterIdDhcpRoute: RouterIdDhcpRoute,
  RouterIdDnsRoute: RouterIdDnsRoute,
  RouterIdFirewallRoute: RouterIdFirewallRouteWithChildren,
  RouterIdLogsRoute: RouterIdLogsRoute,
  RouterIdNetworkRoute: RouterIdNetworkRoute,
  RouterIdPluginsRoute: RouterIdPluginsRoute,
  RouterIdRoutingRoute: RouterIdRoutingRoute,
  RouterIdVlansRoute: RouterIdVlansRoute,
  RouterIdIndexRoute: RouterIdIndexRoute,
  RouterIdServicesInstanceIdRoute: RouterIdServicesInstanceIdRoute,
  RouterIdServicesTemplatesRoute: RouterIdServicesTemplatesRoute,
  RouterIdVpnClientsRoute: RouterIdVpnClientsRoute,
  RouterIdVpnServersRoute: RouterIdVpnServersRoute,
  RouterIdWifiInterfaceNameRoute: RouterIdWifiInterfaceNameRoute,
  RouterIdServicesIndexRoute: RouterIdServicesIndexRoute,
  RouterIdVpnIndexRoute: RouterIdVpnIndexRoute,
  RouterIdWifiIndexRoute: RouterIdWifiIndexRoute,
}

const RouterIdRouteRouteWithChildren = RouterIdRouteRoute._addFileChildren(
  RouterIdRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRouteWithChildren,
  RouterIdRouteRoute: RouterIdRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
